### ISSUE TITLE
Potential Architecture Change

### ISSUE THREAD

**Issue by wagnerlmichael** [ccao-data/model-sales-val#89]
If we decide to move forward with a new sales val strategy. We will need to overhaul config files and meta data output tables.

In terms of inputs we have a [yaml file](https://github.com/ccao-data/model-sales-val/blob/main/manual_flagging/yaml/inputs_initial.yaml) with columns for the groups we use
``` yaml
stat_groups: [
  "rolling_window",
  "township_code",
  "class"
]
```

We have a number of output tables that act as supplementary information to the `sale.flag` table. They are`sale.parameter`, `sale.group_mean`, and `sale.metadata`.

The `sale.parameter` data has the following columns:
- `run_id`
- `sales_flagged`
- `earliest_data_ingest`
- `latest_data_ingest`
- `iso_forest_cols`
- `res_stat_groups`
- `condo_stat_groups` (generated *in* the script by removing a column - potential problem here)
- `dev_bounds`
- `ptax_sd`
- `rolling_window`
- `date_floor`
- `short_term_owner_threshold`
- `min_group_thresh`

The `sale.group_mean` table is comprised of
- `group` - (a single string appended with a `_` separator, for example - `201703_27_295` (rolling_window_township_class) )
- `group_mean`
- `group_std`
- `group_sqft_std`
- `group_sqft_mean`
- `group_size`
- `run_id`

The `sale.metadata` table is comprised of 
- `run_id`
- `long_commit_sha`
- `short_commit_sha`
- `run_timestamp`
- `run_type`

### Groupings that aren't native columns

Right now, the yaml input as a column works nicely with the output structure. In the case of new potential splits. It won't be so clean.  

- New geographies currently ingest from an excel file 
    - Potential solutions
        - Build excel data into an existing table or view? 
- New age and size bins
    - Potential solutions
        - Binning done within sql query

### Update for only a tri
- This new methodology (for now) would only be run on 1 tri. We need to add that option
- Potential solution - add a yaml input as `tris` that could include 1-3

### Different groupings for single/multi-family + condos in the near future
- Single family groups would theoretically contain time window, geographies, size, and age, whereas multi-family would be the same but excluding a size grouping
- The same type of thing will happen when we go to run condo groupings. It is possible that we will decide on yet another distinct set of groups for condos. Currently, the condo groups are dynamically created by dropping an element of a list in the script, we should probably put this into an input config file.
- These changes will probably need to have new columns introduced in the output tables.

### Can old tables and new tables live together?
- Given all of these changes, we can probably expect new meta data columns, or adjusted existing columns. Is there a way to do this and make the old format work with the new? Or should we archive the old tables for now?

### Eventual Glue script change
- This isn't as urgent because we can do all of this with local scripts for the time being. Currently in our glue job we use job parameters instead of a config file. We should think about alternatives to this because it might be messy to try and implement it. Glue job params already only take strings as native input so we are already parsing around that.

**Comment by jeancochrane** [comment]
Some thoughts on the design for the necessary changes following a discussion with @wagnerlmichael:

### Groupings that aren't native columns

> Right now, the yaml input as a column works nicely with the output structure. In the case of new potential splits. It won't be so clean.
>
>  * New geographies currently ingest from an excel file
>    * Potential solutions
>    * Build excel data into an existing table or view?
>  * New age and size bins
>    * Potential solutions
>    * Binning done within sql query

I like the idea of storing an Excel or CSV file in this repo and then writing a helper Python script that we can use to translate it into a Pythonic data structure for use in binning. We may or may not want to reference this data structure in the parameters table, but either way we would be able to reconstruct the geographies used for a given run based on the commit hash.

We could do the same with age and size bins, or we could store their bin definitions in the YAML config file (and by extension the Glue job) since the bin ranges will probably be simpler than the geography groupings.

### Update for only a tri

> * This new methodology (for now) would only be run on 1 tri. We need to add that option
> * Potential solution - add a yaml input as tris that could include 1-3

I like the idea of the YAML input value, and we could also consider adding this to the parameter table!

### Different groupings for single/multi-family + condos in the near future

> * Single family groups would theoretically contain time window, geographies, size, and age, whereas multi-family would be the same but excluding a size grouping
> * The same type of thing will happen when we go to run condo groupings. It is possible that we will decide on yet another distinct set of groups for condos. Currently, the condo groups are dynamically created by dropping an element of a list in the script, we should probably put this into an input config file.
> * These changes will probably need to have new columns introduced in the output tables.

We decided to try treating housing type as a variable that can be set via a YAML input value (or Glue job parameter) such that if different housing types require different groupings we can define different sets of groupings for them via the `stat_groups` parameter.

### Can old tables and new tables live together?

> * Given all of these changes, we can probably expect new meta data columns, or adjusted existing columns. Is there a way to do this and make the old format work with the new? Or should we archive the old tables for now?

We think that as long as we're just adding columns, schema changes to the metadata tables should be fine and should not destroy old data, but Michael is going to confirm this before we move forward.

### Eventual Glue script change

> * This isn't as urgent because we can do all of this with local scripts for the time being. Currently in our glue job we use job parameters instead of a config file. We should think about alternatives to this because it might be messy to try and implement it. Glue job params already only take strings as native input so we are already parsing around that.

Yeah, I also don't love the Glue param system. Ideally I'd like to refactor this project to use [our Batch action](https://github.com/ccao-data/actions/blob/main/.github/workflows/build-and-run-batch-job.yaml) instead of Glue, but that's a little bit speculative at this point. Let's keep an eye on this and I think the constraints of the Glue param system will help us decide how to refactor it.
